### ISSUE TITLE
Add the ability to rename favorites

### ISSUE THREAD

**Issue by fperez** [jupyterlab-contrib/jupyterlab-favorites#5]
Since it's possible to have favorites that point to identically named files or directories living in different locations in the filesystem (e.g. `README.md` files tend to exist everywhere), it would be very useful to be able to rename the actual favorite so the user can pick a more mnemonic identifier.

All bookmark managers in browsers have this feature, and favorites is effectively a  Lab bookmark manager, so it seems like a reasonable addition.

A simple "rename favorite" entry on right-click would do the job, though ideally it would also allow the user to pick a name when creating the entry.

**Comment by fcollonval** [comment]
Thanks for the suggestion @fperez

**Comment by mlucool** [comment]
I was about to log the same issue but with a different solution :)

For me, instead of renaming the favorite, it could give you more information about where it is located without needing to wait for the tooltip. For example, in VSCode, when two files with the same name are opened, it adds location information to the tab in a subtle way:

![image](https://user-images.githubusercontent.com/1813603/164082407-94ffb5c4-6789-4450-9ad0-e45c73262c24.png)

**Comment by marcoschuurman** [comment]
Are you by any chance working on this enhancement? I would love to use a rename functionality as well.

N.B. maybe it's an easy fix to add the full parent path behind the folder name? That info is already included when hovering over a favorite... e.g. 

> Favorite name / (full parent path)

 or something...

**Comment by marcoschuurman** [comment]
Just curious, are you (still) working on this enhancement? I like the idea by @mlucool, just adding the parent path after the favorite name (that info is already available in the link hover). E.g.

> Favorite name / (parent path)
